- renames config option "services" to "anonymity" - fixed update wizard for the specific case when jar file is root protected, but jar directory is not - set relative debug file path in portable mode - show all popup windows on current view (including config view) - show clearer messages when starting forwarding / anti censorship server - some GUI fixes for InfoService panel - some help file updates

diff --git a/InfoService/trunk/install_jondo b/InfoService/trunk/install_jondo
--- a/InfoService/trunk/install_jondo
+++ b/InfoService/trunk/install_jondo
@@ -35,7 +35,7 @@
 JONDOS_HOMEPAGE="https://www.jondos.de"
 
 #default INSTALL_PATH is the users home directory
-INSTALL_PATH=${HOME}
+INSTALL_PATH="/usr/local"
 JAVA_HOME_PATH=${JAVA_HOME}
 JAVA_CMD="java"
 #set placeholders for ant token filtering
@@ -74,7 +74,7 @@ printHelpText()
 	echo " [installpath]/${APPNAME}/${JARNAME}.jar"
 	echo " [installpath]/bin/${APPNAME_LOWERCASE}"
 	echo
-	echo "If not specified installpath defaults to \$HOME or \"/usr/local\", if HOME is not set." 
+	echo "If not specified installpath defaults \"/usr/local\"." 
 	echo
 	echo "Options are:"
 	echo "  -h -?                   shows this help text"
@@ -268,11 +268,11 @@ echo 'case "$1" in' 								>> ${STARTER} || errorStarter
 echo '   --remove)'								>> ${STARTER} || errorStarter
 echo "      if [ ! -w \"${INSTALL_PATH}/${APPNAME}\" -o ! -w \"${STARTER}\" ]; then "\
 										>> ${STARTER} || errorStarter
-echo "         echo \"you are not privileged to remove ${APPNAME}, please run this again as privileged user\""\
+echo "         echo \"You are not privileged to remove ${APPNAME}, please run this again as privileged user!\""\
 										>> ${STARTER} || errorStarter
 echo "         exit 1"  							>> ${STARTER} || errorStarter
 echo "      fi" 								>> ${STARTER} || errorStarter
-echo "      echo \"Uninstallling ${APPNAME}... This will delete:\""		>> ${STARTER} || errorStarter
+echo "      echo \"Uninstalling ${APPNAME}... This will delete:\""		>> ${STARTER} || errorStarter
 echo "      echo \"   1. the directory '${INSTALL_PATH}/${APPNAME}',\""		>> ${STARTER} || errorStarter
 echo "      echo \"   2. the file '${STARTER}'\""				>> ${STARTER} || errorStarter
 echo "      echo \"   3. the ${APPNAME} config and help files\""		>> ${STARTER} || errorStarter
@@ -292,7 +292,7 @@ echo '      ;;'  								>> ${STARTER} || errorStarter
 echo '   --help)'								>> ${STARTER} || errorStarter
 echo "      javaCheck && gcjCheck && \$JAVA_CMD -jar ${INSTALL_PATH}/${APPNAME}/${JARNAME}.jar --help"\
 										>> ${STARTER} || errorStarter
-echo "      echo \"--remove                     Deletes all installed ${APPNAME} file\""\
+echo "      echo \"--remove                     Deletes all installed ${APPNAME} files\""\
 										>> ${STARTER} || errorStarter
 echo "      echo \"                             including directory ${INSTALL_PATH}/${APPNAME} and file ${STARTER}\";;"\
 										>> ${STARTER} || errorStarter
